// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api/hello.dart';
import 'api/profiles.dart';
import 'api/ssh.dart';
import 'dart:async';
import 'dart:convert';
import 'dart:ffi' as ffi;
import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated_io.dart';

abstract class RustLibApiImplPlatform extends BaseApiImpl<RustLibWire> {
  RustLibApiImplPlatform({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw);

  @protected
  RustStreamSink<TerminalSnapshot> dco_decode_StreamSink_terminal_snapshot_Sse(
    dynamic raw,
  );

  @protected
  String dco_decode_String(dynamic raw);

  @protected
  bool dco_decode_bool(dynamic raw);

  @protected
  JumpHost dco_decode_box_autoadd_jump_host(dynamic raw);

  @protected
  Profile dco_decode_box_autoadd_profile(dynamic raw);

  @protected
  Cell dco_decode_cell(dynamic raw);

  @protected
  Color dco_decode_color(dynamic raw);

  @protected
  CommandOutput dco_decode_command_output(dynamic raw);

  @protected
  int dco_decode_i_32(dynamic raw);

  @protected
  JumpHost dco_decode_jump_host(dynamic raw);

  @protected
  List<Cell> dco_decode_list_cell(dynamic raw);

  @protected
  List<int> dco_decode_list_prim_u_8_loose(dynamic raw);

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw);

  @protected
  List<Profile> dco_decode_list_profile(dynamic raw);

  @protected
  String? dco_decode_opt_String(dynamic raw);

  @protected
  Profile dco_decode_profile(dynamic raw);

  @protected
  TerminalSnapshot dco_decode_terminal_snapshot(dynamic raw);

  @protected
  int dco_decode_u_16(dynamic raw);

  @protected
  int dco_decode_u_32(dynamic raw);

  @protected
  BigInt dco_decode_u_64(dynamic raw);

  @protected
  int dco_decode_u_8(dynamic raw);

  @protected
  void dco_decode_unit(dynamic raw);

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer);

  @protected
  RustStreamSink<TerminalSnapshot> sse_decode_StreamSink_terminal_snapshot_Sse(
    SseDeserializer deserializer,
  );

  @protected
  String sse_decode_String(SseDeserializer deserializer);

  @protected
  bool sse_decode_bool(SseDeserializer deserializer);

  @protected
  JumpHost sse_decode_box_autoadd_jump_host(SseDeserializer deserializer);

  @protected
  Profile sse_decode_box_autoadd_profile(SseDeserializer deserializer);

  @protected
  Cell sse_decode_cell(SseDeserializer deserializer);

  @protected
  Color sse_decode_color(SseDeserializer deserializer);

  @protected
  CommandOutput sse_decode_command_output(SseDeserializer deserializer);

  @protected
  int sse_decode_i_32(SseDeserializer deserializer);

  @protected
  JumpHost sse_decode_jump_host(SseDeserializer deserializer);

  @protected
  List<Cell> sse_decode_list_cell(SseDeserializer deserializer);

  @protected
  List<int> sse_decode_list_prim_u_8_loose(SseDeserializer deserializer);

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  List<Profile> sse_decode_list_profile(SseDeserializer deserializer);

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer);

  @protected
  Profile sse_decode_profile(SseDeserializer deserializer);

  @protected
  TerminalSnapshot sse_decode_terminal_snapshot(SseDeserializer deserializer);

  @protected
  int sse_decode_u_16(SseDeserializer deserializer);

  @protected
  int sse_decode_u_32(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer);

  @protected
  int sse_decode_u_8(SseDeserializer deserializer);

  @protected
  void sse_decode_unit(SseDeserializer deserializer);

  @protected
  void sse_encode_AnyhowException(
    AnyhowException self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_StreamSink_terminal_snapshot_Sse(
    RustStreamSink<TerminalSnapshot> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_String(String self, SseSerializer serializer);

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_jump_host(
    JumpHost self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_profile(Profile self, SseSerializer serializer);

  @protected
  void sse_encode_cell(Cell self, SseSerializer serializer);

  @protected
  void sse_encode_color(Color self, SseSerializer serializer);

  @protected
  void sse_encode_command_output(CommandOutput self, SseSerializer serializer);

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_jump_host(JumpHost self, SseSerializer serializer);

  @protected
  void sse_encode_list_cell(List<Cell> self, SseSerializer serializer);

  @protected
  void sse_encode_list_prim_u_8_loose(List<int> self, SseSerializer serializer);

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_profile(List<Profile> self, SseSerializer serializer);

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer);

  @protected
  void sse_encode_profile(Profile self, SseSerializer serializer);

  @protected
  void sse_encode_terminal_snapshot(
    TerminalSnapshot self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_u_16(int self, SseSerializer serializer);

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer);

  @protected
  void sse_encode_unit(void self, SseSerializer serializer);
}

// Section: wire_class

class RustLibWire implements BaseWire {
  factory RustLibWire.fromExternalLibrary(ExternalLibrary lib) =>
      RustLibWire(lib.ffiDynamicLibrary);

  /// Holds the symbol lookup function.
  final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
  _lookup;

  /// The symbols are looked up in [dynamicLibrary].
  RustLibWire(ffi.DynamicLibrary dynamicLibrary)
    : _lookup = dynamicLibrary.lookup;
}
