// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api/hello.dart';
import 'api/profiles.dart';
import 'api/ssh.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Main entrypoint of the Rust API
class RustLib extends BaseEntrypoint<RustLibApi, RustLibApiImpl, RustLibWire> {
  @internal
  static final instance = RustLib._();

  RustLib._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    RustLibApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({required RustLibApi api}) {
    instance.initMockImpl(api: api);
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<RustLibApiImpl, RustLibWire> get apiImplConstructor =>
      RustLibApiImpl.new;

  @override
  WireConstructor<RustLibWire> get wireConstructor =>
      RustLibWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {
    await api.crateApiHelloInitApp();
  }

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.12.0';

  @override
  int get rustContentHash => 990195082;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
        stem: 'rust_lib_tindra',
        ioDirectory: 'rust/target/release/',
        webPrefix: 'pkg/',
        wasmBindgenName: 'wasm_bindgen',
      );
}

abstract class RustLibApi extends BaseApi {
  String crateApiHelloCoreVersion();

  Future<void> crateApiProfilesDeleteProfile({required String id});

  String crateApiHelloEcho({required String msg});

  Future<void> crateApiHelloInitApp();

  Future<List<Profile>> crateApiProfilesListProfiles();

  Future<BigInt> crateApiSshOpenShellPubkey({
    required String host,
    required int port,
    required String username,
    required String privateKeyPath,
    String? passphrase,
    required int cols,
    required int rows,
  });

  Future<String> crateApiProfilesProfilesPath();

  Future<CommandOutput> crateApiSshRunCommandPubkey({
    required String host,
    required int port,
    required String username,
    required String privateKeyPath,
    String? passphrase,
    required String command,
  });

  Future<void> crateApiSshShellClose({required BigInt sessionId});

  Stream<TerminalSnapshot> crateApiSshShellOutputStream({
    required BigInt sessionId,
  });

  Future<void> crateApiSshShellResize({
    required BigInt sessionId,
    required int cols,
    required int rows,
  });

  Future<void> crateApiSshShellWrite({
    required BigInt sessionId,
    required List<int> data,
  });

  Future<Profile> crateApiProfilesUpsertProfile({required Profile profile});
}

class RustLibApiImpl extends RustLibApiImplPlatform implements RustLibApi {
  RustLibApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  String crateApiHelloCoreVersion() {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 1)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiHelloCoreVersionConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiHelloCoreVersionConstMeta =>
      const TaskConstMeta(debugName: "core_version", argNames: []);

  @override
  Future<void> crateApiProfilesDeleteProfile({required String id}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(id, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 2,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiProfilesDeleteProfileConstMeta,
        argValues: [id],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiProfilesDeleteProfileConstMeta =>
      const TaskConstMeta(debugName: "delete_profile", argNames: ["id"]);

  @override
  String crateApiHelloEcho({required String msg}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(msg, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 3)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiHelloEchoConstMeta,
        argValues: [msg],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiHelloEchoConstMeta =>
      const TaskConstMeta(debugName: "echo", argNames: ["msg"]);

  @override
  Future<void> crateApiHelloInitApp() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 4,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiHelloInitAppConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiHelloInitAppConstMeta =>
      const TaskConstMeta(debugName: "init_app", argNames: []);

  @override
  Future<List<Profile>> crateApiProfilesListProfiles() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 5,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_profile,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiProfilesListProfilesConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiProfilesListProfilesConstMeta =>
      const TaskConstMeta(debugName: "list_profiles", argNames: []);

  @override
  Future<BigInt> crateApiSshOpenShellPubkey({
    required String host,
    required int port,
    required String username,
    required String privateKeyPath,
    String? passphrase,
    required int cols,
    required int rows,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(host, serializer);
          sse_encode_u_16(port, serializer);
          sse_encode_String(username, serializer);
          sse_encode_String(privateKeyPath, serializer);
          sse_encode_opt_String(passphrase, serializer);
          sse_encode_u_32(cols, serializer);
          sse_encode_u_32(rows, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 6,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_u_64,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiSshOpenShellPubkeyConstMeta,
        argValues: [
          host,
          port,
          username,
          privateKeyPath,
          passphrase,
          cols,
          rows,
        ],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSshOpenShellPubkeyConstMeta => const TaskConstMeta(
    debugName: "open_shell_pubkey",
    argNames: [
      "host",
      "port",
      "username",
      "privateKeyPath",
      "passphrase",
      "cols",
      "rows",
    ],
  );

  @override
  Future<String> crateApiProfilesProfilesPath() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 7,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiProfilesProfilesPathConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiProfilesProfilesPathConstMeta =>
      const TaskConstMeta(debugName: "profiles_path", argNames: []);

  @override
  Future<CommandOutput> crateApiSshRunCommandPubkey({
    required String host,
    required int port,
    required String username,
    required String privateKeyPath,
    String? passphrase,
    required String command,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(host, serializer);
          sse_encode_u_16(port, serializer);
          sse_encode_String(username, serializer);
          sse_encode_String(privateKeyPath, serializer);
          sse_encode_opt_String(passphrase, serializer);
          sse_encode_String(command, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 8,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_command_output,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiSshRunCommandPubkeyConstMeta,
        argValues: [host, port, username, privateKeyPath, passphrase, command],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSshRunCommandPubkeyConstMeta =>
      const TaskConstMeta(
        debugName: "run_command_pubkey",
        argNames: [
          "host",
          "port",
          "username",
          "privateKeyPath",
          "passphrase",
          "command",
        ],
      );

  @override
  Future<void> crateApiSshShellClose({required BigInt sessionId}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_u_64(sessionId, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 9,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiSshShellCloseConstMeta,
        argValues: [sessionId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSshShellCloseConstMeta =>
      const TaskConstMeta(debugName: "shell_close", argNames: ["sessionId"]);

  @override
  Stream<TerminalSnapshot> crateApiSshShellOutputStream({
    required BigInt sessionId,
  }) {
    final sink = RustStreamSink<TerminalSnapshot>();
    unawaited(
      handler.executeNormal(
        NormalTask(
          callFfi: (port_) {
            final serializer = SseSerializer(generalizedFrbRustBinding);
            sse_encode_u_64(sessionId, serializer);
            sse_encode_StreamSink_terminal_snapshot_Sse(sink, serializer);
            pdeCallFfi(
              generalizedFrbRustBinding,
              serializer,
              funcId: 10,
              port: port_,
            );
          },
          codec: SseCodec(
            decodeSuccessData: sse_decode_unit,
            decodeErrorData: sse_decode_String,
          ),
          constMeta: kCrateApiSshShellOutputStreamConstMeta,
          argValues: [sessionId, sink],
          apiImpl: this,
        ),
      ),
    );
    return sink.stream;
  }

  TaskConstMeta get kCrateApiSshShellOutputStreamConstMeta =>
      const TaskConstMeta(
        debugName: "shell_output_stream",
        argNames: ["sessionId", "sink"],
      );

  @override
  Future<void> crateApiSshShellResize({
    required BigInt sessionId,
    required int cols,
    required int rows,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_u_64(sessionId, serializer);
          sse_encode_u_32(cols, serializer);
          sse_encode_u_32(rows, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 11,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiSshShellResizeConstMeta,
        argValues: [sessionId, cols, rows],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSshShellResizeConstMeta => const TaskConstMeta(
    debugName: "shell_resize",
    argNames: ["sessionId", "cols", "rows"],
  );

  @override
  Future<void> crateApiSshShellWrite({
    required BigInt sessionId,
    required List<int> data,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_u_64(sessionId, serializer);
          sse_encode_list_prim_u_8_loose(data, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 12,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiSshShellWriteConstMeta,
        argValues: [sessionId, data],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSshShellWriteConstMeta => const TaskConstMeta(
    debugName: "shell_write",
    argNames: ["sessionId", "data"],
  );

  @override
  Future<Profile> crateApiProfilesUpsertProfile({required Profile profile}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_box_autoadd_profile(profile, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 13,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_profile,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiProfilesUpsertProfileConstMeta,
        argValues: [profile],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiProfilesUpsertProfileConstMeta =>
      const TaskConstMeta(debugName: "upsert_profile", argNames: ["profile"]);

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return AnyhowException(raw as String);
  }

  @protected
  RustStreamSink<TerminalSnapshot> dco_decode_StreamSink_terminal_snapshot_Sse(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    throw UnimplementedError();
  }

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  bool dco_decode_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as bool;
  }

  @protected
  Profile dco_decode_box_autoadd_profile(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_profile(raw);
  }

  @protected
  Cell dco_decode_cell(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return Cell(
      ch: dco_decode_String(arr[0]),
      fg: dco_decode_color(arr[1]),
      bg: dco_decode_color(arr[2]),
      attrs: dco_decode_u_8(arr[3]),
    );
  }

  @protected
  Color dco_decode_color(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return Color(
      default_: dco_decode_bool(arr[0]),
      r: dco_decode_u_8(arr[1]),
      g: dco_decode_u_8(arr[2]),
      b: dco_decode_u_8(arr[3]),
    );
  }

  @protected
  CommandOutput dco_decode_command_output(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return CommandOutput(
      exitCode: dco_decode_i_32(arr[0]),
      stdout: dco_decode_String(arr[1]),
      stderr: dco_decode_String(arr[2]),
    );
  }

  @protected
  int dco_decode_i_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  List<Cell> dco_decode_list_cell(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_cell).toList();
  }

  @protected
  List<int> dco_decode_list_prim_u_8_loose(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as List<int>;
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  List<Profile> dco_decode_list_profile(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_profile).toList();
  }

  @protected
  String? dco_decode_opt_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_String(raw);
  }

  @protected
  Profile dco_decode_profile(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 7)
      throw Exception('unexpected arr length: expect 7 but see ${arr.length}');
    return Profile(
      id: dco_decode_String(arr[0]),
      name: dco_decode_String(arr[1]),
      host: dco_decode_String(arr[2]),
      port: dco_decode_u_16(arr[3]),
      username: dco_decode_String(arr[4]),
      privateKeyPath: dco_decode_String(arr[5]),
      notes: dco_decode_String(arr[6]),
    );
  }

  @protected
  TerminalSnapshot dco_decode_terminal_snapshot(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 7)
      throw Exception('unexpected arr length: expect 7 but see ${arr.length}');
    return TerminalSnapshot(
      rows: dco_decode_u_32(arr[0]),
      cols: dco_decode_u_32(arr[1]),
      text: dco_decode_String(arr[2]),
      cells: dco_decode_list_cell(arr[3]),
      cursorRow: dco_decode_u_32(arr[4]),
      cursorCol: dco_decode_u_32(arr[5]),
      cursorVisible: dco_decode_bool(arr[6]),
    );
  }

  @protected
  int dco_decode_u_16(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  int dco_decode_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  BigInt dco_decode_u_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeU64(raw);
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_String(deserializer);
    return AnyhowException(inner);
  }

  @protected
  RustStreamSink<TerminalSnapshot> sse_decode_StreamSink_terminal_snapshot_Sse(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    throw UnimplementedError('Unreachable ()');
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  Profile sse_decode_box_autoadd_profile(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_profile(deserializer));
  }

  @protected
  Cell sse_decode_cell(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_ch = sse_decode_String(deserializer);
    var var_fg = sse_decode_color(deserializer);
    var var_bg = sse_decode_color(deserializer);
    var var_attrs = sse_decode_u_8(deserializer);
    return Cell(ch: var_ch, fg: var_fg, bg: var_bg, attrs: var_attrs);
  }

  @protected
  Color sse_decode_color(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_default_ = sse_decode_bool(deserializer);
    var var_r = sse_decode_u_8(deserializer);
    var var_g = sse_decode_u_8(deserializer);
    var var_b = sse_decode_u_8(deserializer);
    return Color(default_: var_default_, r: var_r, g: var_g, b: var_b);
  }

  @protected
  CommandOutput sse_decode_command_output(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_exitCode = sse_decode_i_32(deserializer);
    var var_stdout = sse_decode_String(deserializer);
    var var_stderr = sse_decode_String(deserializer);
    return CommandOutput(
      exitCode: var_exitCode,
      stdout: var_stdout,
      stderr: var_stderr,
    );
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  List<Cell> sse_decode_list_cell(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <Cell>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_cell(deserializer));
    }
    return ans_;
  }

  @protected
  List<int> sse_decode_list_prim_u_8_loose(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  List<Profile> sse_decode_list_profile(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <Profile>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_profile(deserializer));
    }
    return ans_;
  }

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_String(deserializer));
    } else {
      return null;
    }
  }

  @protected
  Profile sse_decode_profile(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_id = sse_decode_String(deserializer);
    var var_name = sse_decode_String(deserializer);
    var var_host = sse_decode_String(deserializer);
    var var_port = sse_decode_u_16(deserializer);
    var var_username = sse_decode_String(deserializer);
    var var_privateKeyPath = sse_decode_String(deserializer);
    var var_notes = sse_decode_String(deserializer);
    return Profile(
      id: var_id,
      name: var_name,
      host: var_host,
      port: var_port,
      username: var_username,
      privateKeyPath: var_privateKeyPath,
      notes: var_notes,
    );
  }

  @protected
  TerminalSnapshot sse_decode_terminal_snapshot(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_rows = sse_decode_u_32(deserializer);
    var var_cols = sse_decode_u_32(deserializer);
    var var_text = sse_decode_String(deserializer);
    var var_cells = sse_decode_list_cell(deserializer);
    var var_cursorRow = sse_decode_u_32(deserializer);
    var var_cursorCol = sse_decode_u_32(deserializer);
    var var_cursorVisible = sse_decode_bool(deserializer);
    return TerminalSnapshot(
      rows: var_rows,
      cols: var_cols,
      text: var_text,
      cells: var_cells,
      cursorRow: var_cursorRow,
      cursorCol: var_cursorCol,
      cursorVisible: var_cursorVisible,
    );
  }

  @protected
  int sse_decode_u_16(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint16();
  }

  @protected
  int sse_decode_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint32();
  }

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getBigUint64();
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_AnyhowException(
    AnyhowException self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.message, serializer);
  }

  @protected
  void sse_encode_StreamSink_terminal_snapshot_Sse(
    RustStreamSink<TerminalSnapshot> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(
      self.setupAndSerialize(
        codec: SseCodec(
          decodeSuccessData: sse_decode_terminal_snapshot,
          decodeErrorData: sse_decode_AnyhowException,
        ),
      ),
      serializer,
    );
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }

  @protected
  void sse_encode_box_autoadd_profile(Profile self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_profile(self, serializer);
  }

  @protected
  void sse_encode_cell(Cell self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.ch, serializer);
    sse_encode_color(self.fg, serializer);
    sse_encode_color(self.bg, serializer);
    sse_encode_u_8(self.attrs, serializer);
  }

  @protected
  void sse_encode_color(Color self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_bool(self.default_, serializer);
    sse_encode_u_8(self.r, serializer);
    sse_encode_u_8(self.g, serializer);
    sse_encode_u_8(self.b, serializer);
  }

  @protected
  void sse_encode_command_output(CommandOutput self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.exitCode, serializer);
    sse_encode_String(self.stdout, serializer);
    sse_encode_String(self.stderr, serializer);
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }

  @protected
  void sse_encode_list_cell(List<Cell> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_cell(item, serializer);
    }
  }

  @protected
  void sse_encode_list_prim_u_8_loose(
    List<int> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(
      self is Uint8List ? self : Uint8List.fromList(self),
    );
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_list_profile(List<Profile> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_profile(item, serializer);
    }
  }

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_String(self, serializer);
    }
  }

  @protected
  void sse_encode_profile(Profile self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.id, serializer);
    sse_encode_String(self.name, serializer);
    sse_encode_String(self.host, serializer);
    sse_encode_u_16(self.port, serializer);
    sse_encode_String(self.username, serializer);
    sse_encode_String(self.privateKeyPath, serializer);
    sse_encode_String(self.notes, serializer);
  }

  @protected
  void sse_encode_terminal_snapshot(
    TerminalSnapshot self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_32(self.rows, serializer);
    sse_encode_u_32(self.cols, serializer);
    sse_encode_String(self.text, serializer);
    sse_encode_list_cell(self.cells, serializer);
    sse_encode_u_32(self.cursorRow, serializer);
    sse_encode_u_32(self.cursorCol, serializer);
    sse_encode_bool(self.cursorVisible, serializer);
  }

  @protected
  void sse_encode_u_16(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint16(self);
  }

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint32(self);
  }

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putBigUint64(self);
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }
}
