// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `fmt`, `from`, `from`

/// All saved profiles, sorted by name.
Future<List<Profile>> listProfiles() =>
    RustLib.instance.api.crateApiProfilesListProfiles();

/// Create a new profile (when `id` is empty) or overwrite an existing one.
Future<Profile> upsertProfile({required Profile profile}) =>
    RustLib.instance.api.crateApiProfilesUpsertProfile(profile: profile);

/// Delete a profile by id. Idempotent — deleting a missing id is a no-op.
Future<void> deleteProfile({required String id}) =>
    RustLib.instance.api.crateApiProfilesDeleteProfile(id: id);

/// Filesystem path of the on-disk profiles file (for diagnostics).
Future<String> profilesPath() =>
    RustLib.instance.api.crateApiProfilesProfilesPath();

class Profile {
  /// Stable id. Empty string when calling upsert for a brand-new profile —
  /// the store will assign one and return it in the result.
  final String id;
  final String name;
  final String host;
  final int port;
  final String username;
  final String privateKeyPath;
  final String notes;

  const Profile({
    required this.id,
    required this.name,
    required this.host,
    required this.port,
    required this.username,
    required this.privateKeyPath,
    required this.notes,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      name.hashCode ^
      host.hashCode ^
      port.hashCode ^
      username.hashCode ^
      privateKeyPath.hashCode ^
      notes.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Profile &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          name == other.name &&
          host == other.host &&
          port == other.port &&
          username == other.username &&
          privateKeyPath == other.privateKeyPath &&
          notes == other.notes;
}
