// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `clone`, `fmt`, `fmt`, `fmt`, `from`, `from`, `from`

/// All saved profiles, sorted by name.
Future<List<Profile>> listProfiles() =>
    RustLib.instance.api.crateApiProfilesListProfiles();

/// Create a new profile (when `id` is empty) or overwrite an existing one.
Future<Profile> upsertProfile({required Profile profile}) =>
    RustLib.instance.api.crateApiProfilesUpsertProfile(profile: profile);

/// Delete a profile by id. Idempotent — deleting a missing id is a no-op.
Future<void> deleteProfile({required String id}) =>
    RustLib.instance.api.crateApiProfilesDeleteProfile(id: id);

/// Filesystem path of the on-disk profiles file (for diagnostics).
Future<String> profilesPath() =>
    RustLib.instance.api.crateApiProfilesProfilesPath();

/// Trusted SSH host keys stored by trust-on-first-use.
Future<List<HostKey>> listHostKeys() =>
    RustLib.instance.api.crateApiProfilesListHostKeys();

/// Check a fingerprint without trusting or updating it.
Future<HostKeyCheck> checkHostKey({
  required String host,
  required int port,
  required String fingerprint,
}) => RustLib.instance.api.crateApiProfilesCheckHostKey(
  host: host,
  port: port,
  fingerprint: fingerprint,
);

/// Store a host key only after explicit user approval.
Future<void> trustHostKey({
  required String host,
  required int port,
  required String fingerprint,
}) => RustLib.instance.api.crateApiProfilesTrustHostKey(
  host: host,
  port: port,
  fingerprint: fingerprint,
);

/// Remove a trusted host key so the next connection can trust a new key.
Future<void> deleteHostKey({required String host, required int port}) =>
    RustLib.instance.api.crateApiProfilesDeleteHostKey(host: host, port: port);

class HostKey {
  final String host;
  final int port;
  final String fingerprint;
  final BigInt firstSeenUnixMs;
  final BigInt lastSeenUnixMs;

  const HostKey({
    required this.host,
    required this.port,
    required this.fingerprint,
    required this.firstSeenUnixMs,
    required this.lastSeenUnixMs,
  });

  @override
  int get hashCode =>
      host.hashCode ^
      port.hashCode ^
      fingerprint.hashCode ^
      firstSeenUnixMs.hashCode ^
      lastSeenUnixMs.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is HostKey &&
          runtimeType == other.runtimeType &&
          host == other.host &&
          port == other.port &&
          fingerprint == other.fingerprint &&
          firstSeenUnixMs == other.firstSeenUnixMs &&
          lastSeenUnixMs == other.lastSeenUnixMs;
}

class HostKeyCheck {
  /// "new", "trusted", or "changed".
  final String status;
  final String expected;
  final String actual;

  const HostKeyCheck({
    required this.status,
    required this.expected,
    required this.actual,
  });

  @override
  int get hashCode => status.hashCode ^ expected.hashCode ^ actual.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is HostKeyCheck &&
          runtimeType == other.runtimeType &&
          status == other.status &&
          expected == other.expected &&
          actual == other.actual;
}

class Profile {
  /// Stable id. Empty string when calling upsert for a brand-new profile —
  /// the store will assign one and return it in the result.
  final String id;
  final String name;
  final String host;
  final int port;
  final String username;
  final String privateKeyPath;
  final String notes;

  /// "key", "agent", or "password". Defaults to "key" when reading older profiles.
  final String authMethod;

  /// Optional jump host. Empty `jump_host` means no jump.
  final String jumpHost;
  final int jumpPort;
  final String jumpUsername;
  final String jumpPrivateKeyPath;

  /// "ssh" (default) or "telnet".
  final String transport;

  const Profile({
    required this.id,
    required this.name,
    required this.host,
    required this.port,
    required this.username,
    required this.privateKeyPath,
    required this.notes,
    required this.authMethod,
    required this.jumpHost,
    required this.jumpPort,
    required this.jumpUsername,
    required this.jumpPrivateKeyPath,
    required this.transport,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      name.hashCode ^
      host.hashCode ^
      port.hashCode ^
      username.hashCode ^
      privateKeyPath.hashCode ^
      notes.hashCode ^
      authMethod.hashCode ^
      jumpHost.hashCode ^
      jumpPort.hashCode ^
      jumpUsername.hashCode ^
      jumpPrivateKeyPath.hashCode ^
      transport.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Profile &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          name == other.name &&
          host == other.host &&
          port == other.port &&
          username == other.username &&
          privateKeyPath == other.privateKeyPath &&
          notes == other.notes &&
          authMethod == other.authMethod &&
          jumpHost == other.jumpHost &&
          jumpPort == other.jumpPort &&
          jumpUsername == other.jumpUsername &&
          jumpPrivateKeyPath == other.jumpPrivateKeyPath &&
          transport == other.transport;
}
