// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `fmt`, `from`, `from`

Future<Settings> loadSettings() =>
    RustLib.instance.api.crateApiSettingsLoadSettings();

Future<void> saveSettings({required Settings settings}) =>
    RustLib.instance.api.crateApiSettingsSaveSettings(settings: settings);

Future<String> settingsPath() =>
    RustLib.instance.api.crateApiSettingsSettingsPath();

Future<String> expectedLogDir() =>
    RustLib.instance.api.crateApiSettingsExpectedLogDir();

Future<String> secretBackend() =>
    RustLib.instance.api.crateApiSettingsSecretBackend();

Future<void> saveSecret({required String name, required String secret}) =>
    RustLib.instance.api.crateApiSettingsSaveSecret(name: name, secret: secret);

Future<String?> loadSecret({required String name}) =>
    RustLib.instance.api.crateApiSettingsLoadSecret(name: name);

Future<void> deleteSecret({required String name}) =>
    RustLib.instance.api.crateApiSettingsDeleteSecret(name: name);

class Settings {
  final String theme;
  final String fontFamily;
  final double fontSize;
  final String quakeHotkey;
  final String locale;
  final String localShell;
  final String localShellCwd;
  final String localShellEnv;

  const Settings({
    required this.theme,
    required this.fontFamily,
    required this.fontSize,
    required this.quakeHotkey,
    required this.locale,
    required this.localShell,
    required this.localShellCwd,
    required this.localShellEnv,
  });

  @override
  int get hashCode =>
      theme.hashCode ^
      fontFamily.hashCode ^
      fontSize.hashCode ^
      quakeHotkey.hashCode ^
      locale.hashCode ^
      localShell.hashCode ^
      localShellCwd.hashCode ^
      localShellEnv.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Settings &&
          runtimeType == other.runtimeType &&
          theme == other.theme &&
          fontFamily == other.fontFamily &&
          fontSize == other.fontSize &&
          quakeHotkey == other.quakeHotkey &&
          locale == other.locale &&
          localShell == other.localShell &&
          localShellCwd == other.localShellCwd &&
          localShellEnv == other.localShellEnv;
}
