// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'ssh.dart';

// These functions are ignored because they are not marked as `pub`: `register_transfer`, `transfer_cancellations_lock`, `transfer_cancellations`, `unregister_transfer`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `fmt`, `fmt`, `from`

Future<bool> cancelSftpTransfer({required String transferId}) =>
    RustLib.instance.api.crateApiSftpCancelSftpTransfer(transferId: transferId);

Future<BigInt> openSftpPubkey({
  required String host,
  required int port,
  required String username,
  required String privateKeyPath,
  String? passphrase,
  required JumpHost jump,
}) => RustLib.instance.api.crateApiSftpOpenSftpPubkey(
  host: host,
  port: port,
  username: username,
  privateKeyPath: privateKeyPath,
  passphrase: passphrase,
  jump: jump,
);

Future<BigInt> openSftpAgent({
  required String host,
  required int port,
  required String username,
  required JumpHost jump,
}) => RustLib.instance.api.crateApiSftpOpenSftpAgent(
  host: host,
  port: port,
  username: username,
  jump: jump,
);

Future<BigInt> openSftpPassword({
  required String host,
  required int port,
  required String username,
  required String password,
  required JumpHost jump,
}) => RustLib.instance.api.crateApiSftpOpenSftpPassword(
  host: host,
  port: port,
  username: username,
  password: password,
  jump: jump,
);

Future<BigInt> openSftpKeyboardInteractive({
  required String host,
  required int port,
  required String username,
  required List<String> responses,
  required JumpHost jump,
}) => RustLib.instance.api.crateApiSftpOpenSftpKeyboardInteractive(
  host: host,
  port: port,
  username: username,
  responses: responses,
  jump: jump,
);

Future<List<SftpEntry>> sftpList({
  required BigInt sessionId,
  required String path,
}) =>
    RustLib.instance.api.crateApiSftpSftpList(sessionId: sessionId, path: path);

Future<BigInt> sftpDownload({
  required BigInt sessionId,
  required String remotePath,
  required String localPath,
}) => RustLib.instance.api.crateApiSftpSftpDownload(
  sessionId: sessionId,
  remotePath: remotePath,
  localPath: localPath,
);

Stream<SftpTransferProgress> sftpDownloadWithProgress({
  required String transferId,
  required BigInt sessionId,
  required String remotePath,
  required String localPath,
  required bool resume,
}) => RustLib.instance.api.crateApiSftpSftpDownloadWithProgress(
  transferId: transferId,
  sessionId: sessionId,
  remotePath: remotePath,
  localPath: localPath,
  resume: resume,
);

Future<BigInt> sftpUpload({
  required BigInt sessionId,
  required String localPath,
  required String remotePath,
}) => RustLib.instance.api.crateApiSftpSftpUpload(
  sessionId: sessionId,
  localPath: localPath,
  remotePath: remotePath,
);

Stream<SftpTransferProgress> sftpUploadWithProgress({
  required String transferId,
  required BigInt sessionId,
  required String localPath,
  required String remotePath,
}) => RustLib.instance.api.crateApiSftpSftpUploadWithProgress(
  transferId: transferId,
  sessionId: sessionId,
  localPath: localPath,
  remotePath: remotePath,
);

Future<void> sftpMakeDir({required BigInt sessionId, required String path}) =>
    RustLib.instance.api.crateApiSftpSftpMakeDir(
      sessionId: sessionId,
      path: path,
    );

Future<void> sftpRemove({
  required BigInt sessionId,
  required String path,
  required bool isDir,
}) => RustLib.instance.api.crateApiSftpSftpRemove(
  sessionId: sessionId,
  path: path,
  isDir: isDir,
);

Future<void> sftpClose({required BigInt sessionId}) =>
    RustLib.instance.api.crateApiSftpSftpClose(sessionId: sessionId);

Future<String> sftpHome({required BigInt sessionId}) =>
    RustLib.instance.api.crateApiSftpSftpHome(sessionId: sessionId);

class SftpEntry {
  final String name;
  final bool isDir;
  final bool isSymlink;
  final BigInt size;
  final BigInt mtime;
  final int permissions;

  const SftpEntry({
    required this.name,
    required this.isDir,
    required this.isSymlink,
    required this.size,
    required this.mtime,
    required this.permissions,
  });

  @override
  int get hashCode =>
      name.hashCode ^
      isDir.hashCode ^
      isSymlink.hashCode ^
      size.hashCode ^
      mtime.hashCode ^
      permissions.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SftpEntry &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          isDir == other.isDir &&
          isSymlink == other.isSymlink &&
          size == other.size &&
          mtime == other.mtime &&
          permissions == other.permissions;
}

class SftpTransferProgress {
  final BigInt bytesTransferred;
  final BigInt totalBytes;
  final bool done;

  const SftpTransferProgress({
    required this.bytesTransferred,
    required this.totalBytes,
    required this.done,
  });

  @override
  int get hashCode =>
      bytesTransferred.hashCode ^ totalBytes.hashCode ^ done.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SftpTransferProgress &&
          runtimeType == other.runtimeType &&
          bytesTransferred == other.bytesTransferred &&
          totalBytes == other.totalBytes &&
          done == other.done;
}
