// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `jump_to_core_pub`, `jump_to_core`, `meta_registry`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `SessionMeta`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `clone`, `clone`, `clone`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `from`

Future<CommandOutput> runCommandPubkey({
  required String host,
  required int port,
  required String username,
  required String privateKeyPath,
  String? passphrase,
  required String command,
}) => RustLib.instance.api.crateApiSshRunCommandPubkey(
  host: host,
  port: port,
  username: username,
  privateKeyPath: privateKeyPath,
  passphrase: passphrase,
  command: command,
);

Future<BigInt> openShellPubkey({
  required String host,
  required int port,
  required String username,
  required String privateKeyPath,
  String? passphrase,
  required int cols,
  required int rows,
  required JumpHost jump,
}) => RustLib.instance.api.crateApiSshOpenShellPubkey(
  host: host,
  port: port,
  username: username,
  privateKeyPath: privateKeyPath,
  passphrase: passphrase,
  cols: cols,
  rows: rows,
  jump: jump,
);

/// Phase 4.0 — open a shell using the local SSH agent for authentication.
Future<BigInt> openShellAgent({
  required String host,
  required int port,
  required String username,
  required int cols,
  required int rows,
  required JumpHost jump,
}) => RustLib.instance.api.crateApiSshOpenShellAgent(
  host: host,
  port: port,
  username: username,
  cols: cols,
  rows: rows,
  jump: jump,
);

/// Stream of terminal snapshots. Bytes from the SSH session are fed into a
/// per-session vt100::Parser; after each chunk a fresh `TerminalSnapshot` is
/// pushed. Call this exactly once per session.
Stream<TerminalSnapshot> shellOutputStream({required BigInt sessionId}) =>
    RustLib.instance.api.crateApiSshShellOutputStream(sessionId: sessionId);

Future<void> shellWrite({required BigInt sessionId, required List<int> data}) =>
    RustLib.instance.api.crateApiSshShellWrite(
      sessionId: sessionId,
      data: data,
    );

/// Resize the remote PTY *and* the local vt100 parser so the next snapshot
/// reflects the new geometry.
Future<void> shellResize({
  required BigInt sessionId,
  required int cols,
  required int rows,
}) => RustLib.instance.api.crateApiSshShellResize(
  sessionId: sessionId,
  cols: cols,
  rows: rows,
);

Future<void> shellClose({required BigInt sessionId}) =>
    RustLib.instance.api.crateApiSshShellClose(sessionId: sessionId);

/// One cell in the terminal grid.
class Cell {
  final String ch;
  final Color fg;
  final Color bg;

  /// Bitfield: 1=bold, 2=italic, 4=underline, 8=inverse, 16=dim.
  final int attrs;

  const Cell({
    required this.ch,
    required this.fg,
    required this.bg,
    required this.attrs,
  });

  @override
  int get hashCode => ch.hashCode ^ fg.hashCode ^ bg.hashCode ^ attrs.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Cell &&
          runtimeType == other.runtimeType &&
          ch == other.ch &&
          fg == other.fg &&
          bg == other.bg &&
          attrs == other.attrs;
}

/// 24-bit color or default. Mirrors tindra_core::term::ColorVal so frb codegen
/// has a local Dart type.
class Color {
  final bool default_;
  final int r;
  final int g;
  final int b;

  const Color({
    required this.default_,
    required this.r,
    required this.g,
    required this.b,
  });

  @override
  int get hashCode => default_.hashCode ^ r.hashCode ^ g.hashCode ^ b.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Color &&
          runtimeType == other.runtimeType &&
          default_ == other.default_ &&
          r == other.r &&
          g == other.g &&
          b == other.b;
}

class CommandOutput {
  final int exitCode;
  final String stdout;
  final String stderr;

  const CommandOutput({
    required this.exitCode,
    required this.stdout,
    required this.stderr,
  });

  @override
  int get hashCode => exitCode.hashCode ^ stdout.hashCode ^ stderr.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CommandOutput &&
          runtimeType == other.runtimeType &&
          exitCode == other.exitCode &&
          stdout == other.stdout &&
          stderr == other.stderr;
}

/// One hop in a jump chain. Empty `host` means "no jump" (sent that way
/// because frb 2.x optional structs are awkward across the bridge).
class JumpHost {
  final String host;
  final int port;
  final String username;
  final String privateKeyPath;
  final String? passphrase;

  const JumpHost({
    required this.host,
    required this.port,
    required this.username,
    required this.privateKeyPath,
    this.passphrase,
  });

  @override
  int get hashCode =>
      host.hashCode ^
      port.hashCode ^
      username.hashCode ^
      privateKeyPath.hashCode ^
      passphrase.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is JumpHost &&
          runtimeType == other.runtimeType &&
          host == other.host &&
          port == other.port &&
          username == other.username &&
          privateKeyPath == other.privateKeyPath &&
          passphrase == other.passphrase;
}

/// One frame of terminal state.
class TerminalSnapshot {
  final int rows;
  final int cols;

  /// Plain-text mirror with `\n` between rows (for selection/search).
  final String text;

  /// Per-cell grid, row-major, length = rows * cols.
  final List<Cell> cells;
  final int cursorRow;
  final int cursorCol;
  final bool cursorVisible;

  const TerminalSnapshot({
    required this.rows,
    required this.cols,
    required this.text,
    required this.cells,
    required this.cursorRow,
    required this.cursorCol,
    required this.cursorVisible,
  });

  @override
  int get hashCode =>
      rows.hashCode ^
      cols.hashCode ^
      text.hashCode ^
      cells.hashCode ^
      cursorRow.hashCode ^
      cursorCol.hashCode ^
      cursorVisible.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TerminalSnapshot &&
          runtimeType == other.runtimeType &&
          rows == other.rows &&
          cols == other.cols &&
          text == other.text &&
          cells == other.cells &&
          cursorRow == other.cursorRow &&
          cursorCol == other.cursorCol &&
          cursorVisible == other.cursorVisible;
}
