// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `meta_registry`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `SessionMeta`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `fmt`, `fmt`, `from`

Future<CommandOutput> runCommandPubkey({
  required String host,
  required int port,
  required String username,
  required String privateKeyPath,
  String? passphrase,
  required String command,
}) => RustLib.instance.api.crateApiSshRunCommandPubkey(
  host: host,
  port: port,
  username: username,
  privateKeyPath: privateKeyPath,
  passphrase: passphrase,
  command: command,
);

Future<BigInt> openShellPubkey({
  required String host,
  required int port,
  required String username,
  required String privateKeyPath,
  String? passphrase,
  required int cols,
  required int rows,
}) => RustLib.instance.api.crateApiSshOpenShellPubkey(
  host: host,
  port: port,
  username: username,
  privateKeyPath: privateKeyPath,
  passphrase: passphrase,
  cols: cols,
  rows: rows,
);

/// Stream of terminal snapshots. Bytes from the SSH session are fed into a
/// per-call `vt100::Parser`, and after each chunk a fresh `TerminalSnapshot`
/// is pushed to the sink. Call this exactly once per session.
Stream<TerminalSnapshot> shellOutputStream({required BigInt sessionId}) =>
    RustLib.instance.api.crateApiSshShellOutputStream(sessionId: sessionId);

Future<void> shellWrite({required BigInt sessionId, required List<int> data}) =>
    RustLib.instance.api.crateApiSshShellWrite(
      sessionId: sessionId,
      data: data,
    );

Future<void> shellResize({
  required BigInt sessionId,
  required int cols,
  required int rows,
}) => RustLib.instance.api.crateApiSshShellResize(
  sessionId: sessionId,
  cols: cols,
  rows: rows,
);

Future<void> shellClose({required BigInt sessionId}) =>
    RustLib.instance.api.crateApiSshShellClose(sessionId: sessionId);

class CommandOutput {
  final int exitCode;
  final String stdout;
  final String stderr;

  const CommandOutput({
    required this.exitCode,
    required this.stdout,
    required this.stderr,
  });

  @override
  int get hashCode => exitCode.hashCode ^ stdout.hashCode ^ stderr.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CommandOutput &&
          runtimeType == other.runtimeType &&
          exitCode == other.exitCode &&
          stdout == other.stdout &&
          stderr == other.stderr;
}

/// One frame of terminal state, ready to be rendered as monospace text.
class TerminalSnapshot {
  final int rows;
  final int cols;
  final String text;
  final int cursorRow;
  final int cursorCol;
  final bool cursorVisible;

  const TerminalSnapshot({
    required this.rows,
    required this.cols,
    required this.text,
    required this.cursorRow,
    required this.cursorCol,
    required this.cursorVisible,
  });

  @override
  int get hashCode =>
      rows.hashCode ^
      cols.hashCode ^
      text.hashCode ^
      cursorRow.hashCode ^
      cursorCol.hashCode ^
      cursorVisible.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TerminalSnapshot &&
          runtimeType == other.runtimeType &&
          rows == other.rows &&
          cols == other.cols &&
          text == other.text &&
          cursorRow == other.cursorRow &&
          cursorCol == other.cursorCol &&
          cursorVisible == other.cursorVisible;
}
